build and update the unity image

diff --git a/unity/build-kernel b/unity/build-kernel
--- a/unity/build-kernel
+++ b/unity/build-kernel
@@ -1,7 +1,17 @@
 #!/bin/bash
 
+die() {
+	echo "$*" 1>&2
+	exit 1
+}
+
 HOST=${1:-localhost}
 PORT=${2:-5555}
+
+LSM=${LSM:-$(pwd)/lsm}
+export LSM
+
+LSM_REPO=${LSM_REPO:-git@github.com:starlab-io/galahad-lsm}
 
 echo "Getting the kernel release from the running cloud-image at ${HOST}:${PORT}"
 VERSION=$(ssh -o "ControlMaster=yes" -p ${PORT} ubuntu@${HOST} uname -r)
@@ -13,5 +23,19 @@ CODENAME=$(ssh -o "ControlMaster=yes" -p ${PORT} ubuntu@${HOST} "source /etc/lsb
 export CODENAME
 echo "Found distro codename '${CODENAME}'"
 
+echo "Fetching down the latest LSM"
+if [[ ! -d ${LSM} ]]; then
+	git clone ${LSM_REPO} ${LSM} || die "Failed to clone LSM from ${LSM_REPO} into ${LSM}"
+fi
+
 echo "Firing up a docker container to build the kernel..."
-./containerize.sh ./helpers/build-kernel
+./containerize.sh ./helpers/build-kernel || die "Failed to build the kernel"
+
+scp -P${PORT} kernel-source/linux-image-[0-9].*.deb ubuntu@${HOST}:
+scp -P${PORT} kernel-source/linux-headers-*.deb ubuntu@${HOST}:
+
+ssh -p ${PORT} ubuntu@${HOST} <<  END
+sudo dpkg -i --force *.deb
+rm *.deb
+sudo reboot
+END
