Added locks for map initialization; updated comment on ruleset structure

diff --git a/transducers/actuators/networkactuator/netblock b/transducers/actuators/networkactuator/netblock
--- a/transducers/actuators/networkactuator/netblock
+++ b/transducers/actuators/networkactuator/netblock
@@ -10,7 +10,14 @@ then
 	exit 0
 fi
 
-usage(){ echo "USAGE: netblock [block|unblock] [incoming|outgoing] [ipv4|ipv6|tcp|udp] <value>"; }
+if [ "$*" == "reset" ]
+then
+	sudo printf "%s" "reset" >> /dev/netblockchar
+	> $FILE
+	exit 0
+fi
+
+usage(){ echo "USAGE: netblock [block|unblock] [incoming|outgoing] [src|dst] [ipv4|ipv6|tcp|udp] <value>"; }
 
 #Verify string is a valid IPv4 address
 ipv4check(){
@@ -50,6 +57,17 @@ else
 fi
 }
 
+ipportcheck(){
+ipport=$1
+ipportRegex="^(((\d{1,3}\.){3}\d{1,3})|(([0-9a-z]{4}\:){7}[0-9a-z]{4}))\:(\d{1,5})$"
+if [[ $ippor =~ $ipportRegex ]];
+then
+	return "1"
+else
+	return "0"
+fi
+}
+
 # Verify command arguments order
 if [[ "$1" != "block" && "$1" != "unblock" ]]
 then
@@ -69,7 +87,7 @@ then
 	exit 1
 fi
 
-if [[ "$4" != "tcp" && "$4" != "udp" && "$4" != "ipv4" && "$4" != "ipv6" ]]
+if [[ "$4" != "tcp" && "$4" != "udp" && "$4" != "ipv4" && "$4" != "ipv6"  && "$4" != "ipport" ]]
 then
 	usage
 	exit 1
@@ -115,6 +133,19 @@ then
 		value="$5"
 	fi
 fi
+
+#if [[ "$4" == "ipport" ]]
+#then
+#	ipportcheck $5
+#	if [ "$?" -eq "0" ]
+#	then
+#		echo "Invalid ip:port combo"
+#		usage
+#		exit 1
+#	else
+#		value="$5"
+#	fi
+#fi
 
 args="$1 $2 $3 $4 $value"
 #Run commands
